/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import entidades.Cliente;
import entidades.DetalleVenta;
import entidades.Usuario;
import entidades.Venta;
import fachada.FachadaControl;
import interfaces.IFachadaControl;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jarol
 */
public class ReporteVentaForm extends javax.swing.JFrame {

    /**
     * Creates new form ReporteVentaForm
     */
      private static ReporteVentaForm reporteVenta; 
      private IFachadaControl logica;
      private List<Cliente> clientes;
      
    public ReporteVentaForm() {
        initComponents();
         logica = new FachadaControl();
         ventas = logica.consultarVentas();
         llenarTabla();
          llenarCBoxClientes();
         this.setLocationRelativeTo(null);
    }

    public static ReporteVentaForm instanciaCerrarCaja() {
        if (reporteVenta == null) {
            reporteVenta = new ReporteVentaForm();
        }
        return reporteVenta;
    }
    
    public void llenarCBoxClientes() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        clientes = logica.consultarTodosClientes();
        for (int i = 0; i < clientes.size(); i++) {
            Cliente get = clientes.get(i);
            model.addElement(get.getNombre());
        }
        clientesC.setModel(model);
    }
    
     private List<Venta> ventas;
       private void llenarTabla() {
       
        if (ventas != null || !ventas.isEmpty()) {
            DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaVentas.getModel();
            this.tablaVentas.setRowHeight(30);
            modeloTabla.setRowCount(0);
            ventas.forEach(venta -> {
                Object[] fila = new Object[7];
                fila[0] = venta.getId().toString();
                fila[1] = venta.getFecha().get(Calendar.DAY_OF_MONTH)+"/"+venta.getFecha().get(Calendar.MONTH)+"/"+venta.getFecha().get(Calendar.YEAR);
                fila[2] = venta.getNumTicket();
                fila[3] = venta.getTotalventa();  
                fila[4] = venta.getCaja().getId();
                fila[5] = venta.getCliente().getId();
                 fila[6] = venta.getCliente().getNombre();
                modeloTabla.addRow(fila);
            });
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        clientesC = new javax.swing.JComboBox<>();
        lblCliente = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnTodas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalles = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new GUIs.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 778));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha", "Num Ticket", "Total Venta", "Id Caja", "Id Cliente", "Nombre Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 520, 370));

        clientesC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesCActionPerformed(evt);
            }
        });
        jPanel1.add(clientesC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, -1));

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCliente.setText("Cliente:");
        jPanel1.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(204, 204, 255), java.awt.Color.white));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 110, 30));

        btnTodas.setBackground(new java.awt.Color(0, 0, 255));
        btnTodas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTodas.setForeground(new java.awt.Color(255, 255, 255));
        btnTodas.setText("Todas");
        btnTodas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(204, 204, 255), java.awt.Color.white));
        btnTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasActionPerformed(evt);
            }
        });
        jPanel1.add(btnTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 110, 30));

        tablaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdProducto", "Nombre", "Cantidad", "Precio vendido", "idVenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaDetalles);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 420, 590));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Detalles");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, -1, -1));

        panelRound1.setBackground(new java.awt.Color(70, 4, 129));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1000, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesCActionPerformed

    }//GEN-LAST:event_clientesCActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
       String cliente= clientesC.getSelectedItem().toString();
       ventas.clear();
       ventas=logica.consultarVentas();
       for (int i = ventas.size() - 1; i >= 0; i--) {
    Venta venta = ventas.get(i);
    if (!venta.getCliente().getNombre().equals(cliente)) {
        ventas.remove(i);
    }
}

       
          llenarTabla();
       
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasActionPerformed
        ventas = logica.consultarVentas();
         llenarTabla();
        
    }//GEN-LAST:event_btnTodasActionPerformed
  private List<DetalleVenta> detalles;
       private void llenarTabladetalles() {
       
        if (detalles != null || !detalles.isEmpty()) {
            DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaDetalles.getModel();
            this.tablaDetalles.setRowHeight(30);
            modeloTabla.setRowCount(0);
            detalles.forEach(venta -> {
                Object[] fila = new Object[5];
                fila[0] = venta.getProducto().getId();
                fila[1] = venta.getProducto().getNombre();
                fila[2] = venta.getCantidad();
                fila[3] = venta.getPrecioVendido();  
                fila[4] = venta.getVenta().getId();
               
                modeloTabla.addRow(fila);
            });
        }

    }
       private void limpiarTablaDetalles() {
    DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaDetalles.getModel();
    modeloTabla.setRowCount(0);
}

       
    private void tablaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentasMouseClicked
   limpiarTablaDetalles();
        int seleccionado=tablaVentas.rowAtPoint(evt.getPoint());
        String idVenta=tablaVentas.getValueAt(seleccionado,0).toString();
      //   List<DetalleVenta> detalleVenta;
        detalles=logica.consultarTodasDetallesVentas();
    
     
       
       for (int i = 0; i < detalles.size(); i++) {
    DetalleVenta detalle = detalles.get(i);
    if (!detalle.getVenta().getId().equals(idVenta)) {
        detalles.remove(i);
    }
}
       
      llenarTabladetalles();

    }//GEN-LAST:event_tablaVentasMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setVisible(false);
      
        dispose();
        PrincipalForm.getInstance().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnTodas;
    private javax.swing.JComboBox<String> clientesC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCliente;
    private GUIs.PanelRound panelRound1;
    private javax.swing.JTable tablaDetalles;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
