package GUIs;

import entidades.Caja;
import enumeradores.Estado;
import fachada.FachadaControl;
import interfaces.IFachadaControl;
import javax.swing.JOptionPane;

public class PrincipalForm extends javax.swing.JFrame {

    private IFachadaControl fachadaControl;
    private static PrincipalForm principalForm;

    /**
     * Creates new form PrincipalForm
     */
    private PrincipalForm() {
        initComponents();
        fachadaControl = new FachadaControl();
    }

    public static PrincipalForm getInstance() {
        if (principalForm == null) {
            principalForm = new PrincipalForm();
        }
        return principalForm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCaja = new javax.swing.JMenu();
        menuCajaNuevoTicket = new javax.swing.JMenuItem();
        menuCajaAbrirCaja = new javax.swing.JMenuItem();
        menuCajaCierreCaja = new javax.swing.JMenuItem();
        MenuAdmin = new javax.swing.JMenu();
        MenuAdminCategoria = new javax.swing.JMenuItem();
        MenuAdminClientes = new javax.swing.JMenuItem();
        MenuAdminProductos = new javax.swing.JMenuItem();
        MenuAdminProveedores = new javax.swing.JMenuItem();
        MenuAdminUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1000, 750));
        pnlPrincipal.setLayout(new java.awt.CardLayout());

        MenuCaja.setText("Caja");

        menuCajaNuevoTicket.setText("Nueva Venta");
        menuCajaNuevoTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCajaNuevoTicketActionPerformed(evt);
            }
        });
        MenuCaja.add(menuCajaNuevoTicket);

        menuCajaAbrirCaja.setText("Abrir Nueva Caja");
        menuCajaAbrirCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCajaAbrirCajaActionPerformed(evt);
            }
        });
        MenuCaja.add(menuCajaAbrirCaja);

        menuCajaCierreCaja.setText("Cierre de Caja");
        menuCajaCierreCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCajaCierreCajaActionPerformed(evt);
            }
        });
        MenuCaja.add(menuCajaCierreCaja);

        jMenuBar1.add(MenuCaja);

        MenuAdmin.setText("Administrar");

        MenuAdminCategoria.setText("Categorias");
        MenuAdminCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdminCategoriaActionPerformed(evt);
            }
        });
        MenuAdmin.add(MenuAdminCategoria);

        MenuAdminClientes.setText("Clientes");
        MenuAdminClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdminClientesActionPerformed(evt);
            }
        });
        MenuAdmin.add(MenuAdminClientes);

        MenuAdminProductos.setText("Productos");
        MenuAdminProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdminProductosActionPerformed(evt);
            }
        });
        MenuAdmin.add(MenuAdminProductos);

        MenuAdminProveedores.setText("Proveedores");
        MenuAdminProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdminProveedoresActionPerformed(evt);
            }
        });
        MenuAdmin.add(MenuAdminProveedores);

        MenuAdminUsuario.setText("Usuario");
        MenuAdminUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdminUsuarioActionPerformed(evt);
            }
        });
        MenuAdmin.add(MenuAdminUsuario);

        jMenuBar1.add(MenuAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCajaNuevoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCajaNuevoTicketActionPerformed

        //Aqui habra una validacion con el fin de que validamos el usario actual, el metodo de consultar caja abierta
        //verifica si el usuario corresponde a la sesion
        Caja caja = fachadaControl.consultarCajaAbierta();
        if (caja != null) {
            this.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    VentasForm.getInstance().setVisible(true);
                    VentasForm.getInstance().establecerCaja(caja);
                }
            });
        } else {
            JOptionPane.showMessageDialog(null, "No se ha registrado alguna caja se requiere que abra alguna");
        }
    }//GEN-LAST:event_menuCajaNuevoTicketActionPerformed

    private void MenuAdminUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdminUsuarioActionPerformed

        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdmiUsuarioForm.getInstance().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuAdminUsuarioActionPerformed

    private void MenuAdminCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdminCategoriaActionPerformed
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdmiCategoria.getInstance().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuAdminCategoriaActionPerformed

    private void MenuAdminClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdminClientesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdmiClienteForm.getInstance().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuAdminClientesActionPerformed

    private void MenuAdminProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdminProductosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdmiProductoForm.getInstance().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuAdminProductosActionPerformed

    private void MenuAdminProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdminProveedoresActionPerformed

        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdmiProveedorForm.getInstance().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuAdminProveedoresActionPerformed

    private void menuCajaAbrirCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCajaAbrirCajaActionPerformed
    //Aqui habra una validacion con el fin de que validamos el usario actual, el metodo de consultar caja abierta
        //verifica si el usuario corresponde a la sesions
        Caja caja = fachadaControl.consultarCajaAbierta();
        if (caja != null) {
            JOptionPane.showMessageDialog(null, "No se ha cerrado la caja actual, requiere cerrarla");
        } else {
            this.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    AbrirCajaForm.instanciaAbrirCaja().setVisible(true);
                }
            });
        }
    }//GEN-LAST:event_menuCajaAbrirCajaActionPerformed

    private void menuCajaCierreCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCajaCierreCajaActionPerformed
        //Aqui habra una validacion con el fin de que validamos el usario actual, el metodo de consultar caja abierta
        //verifica si el usuario corresponde a la sesion
        JOptionPane.showMessageDialog(null, "El cierre de caja, aun no se implementa espera actualizaciones y casos de uso");
//        Caja caja=new Caja(fechaApertura, TOP_ALIGNMENT, TOP_ALIGNMENT, TOP_ALIGNMENT, TOP_ALIGNMENT, Estado.CERRADA, usuario)
    }//GEN-LAST:event_menuCajaCierreCajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenuItem MenuAdminCategoria;
    private javax.swing.JMenuItem MenuAdminClientes;
    private javax.swing.JMenuItem MenuAdminProductos;
    private javax.swing.JMenuItem MenuAdminProveedores;
    private javax.swing.JMenuItem MenuAdminUsuario;
    private javax.swing.JMenu MenuCaja;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCajaAbrirCaja;
    private javax.swing.JMenuItem menuCajaCierreCaja;
    private javax.swing.JMenuItem menuCajaNuevoTicket;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
